### ISSUE TITLE
Add a subcommand "-u" to re-mark a completed task as uncompleted.

### ISSUE THREAD

**Issue by abgox** [jjw24/Wox.Plugin.Todos#3]
- Sometimes tasks are incorrectly marked as completed, or  it's times to re-mark a completed task as uncompleted.
- It should have a command to handle it.
- I recommend using "-u", which means undo.

**Comment by Or1g3n** [comment]
@abgox 
The feature you have requested as well as some other enhancements have been incorporated into a fork of this project; see https://github.com/Or1g3n/Flow.Launcher.Plugin.Todos. Per discussion with the current developer (jjw24), the Todos plugin will be resourced to the above fork once PR for plugin manifest has been gone through approvals (would expect within a week or so). In the meantime, feel free to download the .zip from the release page of the fork and paste contents into the plugin directory. Hope this satisfies what you were looking for!

**Comment by abgox** [comment]
thanks.
